#=============================================#
#                 v.1.2.8                     #  
                 CLING-MD
#     𝗠𝗨𝗟𝗧𝗜𝗗𝗘𝗩𝗜𝗖𝗘 𝗪𝗛𝗔𝗧𝗦𝗔𝗣𝗣 𝗨𝗦𝗘𝗥 𝗕𝗢𝗧        #
#=============================================#
# 
#    * @project_name : Cling-Md
#    * @author : @𓅓𝙒𝞖𝞘𝙕𓅓
#    * @youtube :
#    * @description : Cling-Md ,A Multi-functional whatsapp bot md.
#    * @version 1.2.8
# 
# Don't change this [ /SuhailTechInfo/ ] name!
# Change from below link, else bot not works!

 

FROM quay.io/𓅓𝙒𝞖𝞘𝙕𓅓
RUN git clone https://github.com/whizmburu/cling/root/Whiz
WORKDIR /root/whiz/
RUN npm install
EXPOSE 8000
CMD ["npm","start" ] 
