#=============================================#
#                 v.1.2.8                     #  
#             CLING MD                       #
#     𝗠𝗨𝗟𝗧𝗜𝗗𝗘𝗩𝗜𝗖𝗘 𝗪𝗛𝗔𝗧𝗦𝗔𝗣𝗣 𝗨𝗦𝗘𝗥 𝗕𝗢𝗧        #
#=============================================#
# 
#    * @project_name : Cling-Md
#    * @author : @whiz
#    * @youtube : whiz @254754783683
#    * @description : Whiz-Md ,A Multi-functional whatsapp bot md.
#    * @version 1.2.8
# 
# Don't change this [ /whizmburu/ ] name!
# Change from below link, else bot not works!

 

FROM quay.io/suhailtechinfo/suhail-v2
RUN git clone https://github.com/whizmburu/cling-Md/root/Suhail
WORKDIR /root/whiz/
RUN npm install
EXPOSE 8000
CMD ["npm","start" ] 
